sudo: required

before_script:
  - bundle exec rails db:create db:migrate

cache: bundler
language: ruby
rvm:
 - 2.3.1
script:

  - bundle exec rspec
dist: xenial

# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
